nohup: ignoring input
/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
create_global_tag_statuses()
get_existing_global_tag_statuses()
res.json() = [{'id': 17, 'name': 'unlocked', 'created': '2023-02-03T15:52:41.743025'}]
create_global_tags()
get_existing_global_tags()
res.json() = [{'id': 17, 'name': 'global_tag_0', 'author': 'linogerlach', 'status': 'unlocked', 'payload_lists_count': 1, 'payload_iov_count': 50000, 'created': '2023-02-03T15:52:41.774769', 'updated': '2023-02-03T15:52:41.847378'}]
get_exisitng_payload_types()
res.json() = [{'id': 71, 'name': 'pl_type_0', 'created': '2023-02-03T15:52:41.800361'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
gt global_tag_0 already has a pl for type pl_type_0
get_last_plt_iov_dict()
url = http://test111.apps.usatlas.bnl.gov/api/cdb_rest/payloadiovsfast/?gtName=global_tag_0&majorIOV=2147483647&minorIOV=0
resp.json() = [{'id': 71, 'name': 'pl_type_0_71', 'global_tag': 'global_tag_0', 'payload_type': 'pl_type_0', 'payload_iov': [{'id': 6595005, 'payload_url': 'pl_type_0_71_49999_dummy_file.data', 'checksum': '', 'major_iov': 49999, 'minor_iov': 0, 'major_iov_end': 9223372036854775807, 'minor_iov_end': 9223372036854775807, 'payload_list': 'pl_type_0_71', 'inserted': '2023-02-03T15:53:41.051324'}], 'created': '2023-02-03T15:52:41.830414'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
starting to inserting iovs from 50000 to 50000 into pll pl_type_0_71
sdcc.json
resp = ['']
line = 
Traceback (most recent call last):
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 36, in <module>
    main(args)
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 11, in main
    campaign.prepare()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 186, in prepare
    self.set_db_size_dict()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 177, in set_db_size_dict
    x_dict = json.loads(line)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
create_global_tag_statuses()
get_existing_global_tag_statuses()
res.json() = [{'id': 17, 'name': 'unlocked', 'created': '2023-02-03T15:52:41.743025'}]
create_global_tags()
get_existing_global_tags()
res.json() = [{'id': 17, 'name': 'global_tag_0', 'author': 'linogerlach', 'status': 'unlocked', 'payload_lists_count': 1, 'payload_iov_count': 50000, 'created': '2023-02-03T15:52:41.774769', 'updated': '2023-02-03T15:52:41.847378'}]
get_exisitng_payload_types()
res.json() = [{'id': 71, 'name': 'pl_type_0', 'created': '2023-02-03T15:52:41.800361'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
gt global_tag_0 already has a pl for type pl_type_0
get_last_plt_iov_dict()
url = http://test111.apps.usatlas.bnl.gov/api/cdb_rest/payloadiovsfast/?gtName=global_tag_0&majorIOV=2147483647&minorIOV=0
resp.json() = [{'id': 71, 'name': 'pl_type_0_71', 'global_tag': 'global_tag_0', 'payload_type': 'pl_type_0', 'payload_iov': [{'id': 6595005, 'payload_url': 'pl_type_0_71_49999_dummy_file.data', 'checksum': '', 'major_iov': 49999, 'minor_iov': 0, 'major_iov_end': 9223372036854775807, 'minor_iov_end': 9223372036854775807, 'payload_list': 'pl_type_0_71', 'inserted': '2023-02-03T15:53:41.051324'}], 'created': '2023-02-03T15:52:41.830414'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
starting to inserting iovs from 50000 to 50000 into pll pl_type_0_71
sdcc.json
resp = ['']
line = 
Traceback (most recent call last):
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 36, in <module>
    main(args)
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 11, in main
    campaign.prepare()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 186, in prepare
    self.set_db_size_dict()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 177, in set_db_size_dict
    x_dict = json.loads(line)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
create_global_tag_statuses()
get_existing_global_tag_statuses()
res.json() = [{'id': 17, 'name': 'unlocked', 'created': '2023-02-03T15:52:41.743025'}]
create_global_tags()
get_existing_global_tags()
res.json() = [{'id': 17, 'name': 'global_tag_0', 'author': 'linogerlach', 'status': 'unlocked', 'payload_lists_count': 1, 'payload_iov_count': 50000, 'created': '2023-02-03T15:52:41.774769', 'updated': '2023-02-03T15:52:41.847378'}]
get_exisitng_payload_types()
res.json() = [{'id': 71, 'name': 'pl_type_0', 'created': '2023-02-03T15:52:41.800361'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
gt global_tag_0 already has a pl for type pl_type_0
get_last_plt_iov_dict()
url = http://test111.apps.usatlas.bnl.gov/api/cdb_rest/payloadiovsfast/?gtName=global_tag_0&majorIOV=2147483647&minorIOV=0
resp.json() = [{'id': 71, 'name': 'pl_type_0_71', 'global_tag': 'global_tag_0', 'payload_type': 'pl_type_0', 'payload_iov': [{'id': 6595005, 'payload_url': 'pl_type_0_71_49999_dummy_file.data', 'checksum': '', 'major_iov': 49999, 'minor_iov': 0, 'major_iov_end': 9223372036854775807, 'minor_iov_end': 9223372036854775807, 'payload_list': 'pl_type_0_71', 'inserted': '2023-02-03T15:53:41.051324'}], 'created': '2023-02-03T15:52:41.830414'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
starting to inserting iovs from 50000 to 50000 into pll pl_type_0_71
sdcc.json
resp = ['']
line = 
Traceback (most recent call last):
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 36, in <module>
    main(args)
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 11, in main
    campaign.prepare()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 186, in prepare
    self.set_db_size_dict()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 177, in set_db_size_dict
    x_dict = json.loads(line)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
create_global_tag_statuses()
get_existing_global_tag_statuses()
res.json() = [{'id': 17, 'name': 'unlocked', 'created': '2023-02-03T15:52:41.743025'}]
create_global_tags()
get_existing_global_tags()
res.json() = [{'id': 17, 'name': 'global_tag_0', 'author': 'linogerlach', 'status': 'unlocked', 'payload_lists_count': 1, 'payload_iov_count': 50000, 'created': '2023-02-03T15:52:41.774769', 'updated': '2023-02-03T15:52:41.847378'}]
get_exisitng_payload_types()
res.json() = [{'id': 71, 'name': 'pl_type_0', 'created': '2023-02-03T15:52:41.800361'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
gt global_tag_0 already has a pl for type pl_type_0
get_last_plt_iov_dict()
url = http://test111.apps.usatlas.bnl.gov/api/cdb_rest/payloadiovsfast/?gtName=global_tag_0&majorIOV=2147483647&minorIOV=0
resp.json() = [{'id': 71, 'name': 'pl_type_0_71', 'global_tag': 'global_tag_0', 'payload_type': 'pl_type_0', 'payload_iov': [{'id': 6595005, 'payload_url': 'pl_type_0_71_49999_dummy_file.data', 'checksum': '', 'major_iov': 49999, 'minor_iov': 0, 'major_iov_end': 9223372036854775807, 'minor_iov_end': 9223372036854775807, 'payload_list': 'pl_type_0_71', 'inserted': '2023-02-03T15:53:41.051324'}], 'created': '2023-02-03T15:52:41.830414'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
starting to inserting iovs from 50000 to 100000 into pll pl_type_0_71
inserting 5000 iovs... 
<Response [200]>
inserting 5000 iovs... 
<Response [200]>
inserting 5000 iovs... 
<Response [200]>
inserting 5000 iovs... 
<Response [200]>
inserting 5000 iovs... 
<Response [200]>
inserting 5000 iovs... 
<Response [200]>
inserting 5000 iovs... 
<Response [200]>
inserting 5000 iovs... 
<Response [200]>
inserting 5000 iovs... 
<Response [200]>
inserting 5000 iovs... 
<Response [200]>
sdcc.json
resp = ['']
line = 
Traceback (most recent call last):
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 36, in <module>
    main(args)
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 11, in main
    campaign.prepare()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 186, in prepare
    self.set_db_size_dict()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 177, in set_db_size_dict
    x_dict = json.loads(line)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
create_global_tag_statuses()
get_existing_global_tag_statuses()
res.json() = [{'id': 17, 'name': 'unlocked', 'created': '2023-02-03T15:52:41.743025'}]
create_global_tags()
get_existing_global_tags()
res.json() = [{'id': 17, 'name': 'global_tag_0', 'author': 'linogerlach', 'status': 'unlocked', 'payload_lists_count': 1, 'payload_iov_count': 100000, 'created': '2023-02-03T15:52:41.774769', 'updated': '2023-02-03T15:52:41.847378'}]
get_exisitng_payload_types()
res.json() = [{'id': 71, 'name': 'pl_type_0', 'created': '2023-02-03T15:52:41.800361'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
gt global_tag_0 already has a pl for type pl_type_0
get_last_plt_iov_dict()
url = http://test111.apps.usatlas.bnl.gov/api/cdb_rest/payloadiovsfast/?gtName=global_tag_0&majorIOV=2147483647&minorIOV=0
resp.json() = [{'id': 71, 'name': 'pl_type_0_71', 'global_tag': 'global_tag_0', 'payload_type': 'pl_type_0', 'payload_iov': [{'id': 6645005, 'payload_url': 'pl_type_0_71_99999_dummy_file.data', 'checksum': '', 'major_iov': 99999, 'minor_iov': 0, 'major_iov_end': 9223372036854775807, 'minor_iov_end': 9223372036854775807, 'payload_list': 'pl_type_0_71', 'inserted': '2023-02-06T08:37:00.635522'}], 'created': '2023-02-03T15:52:41.830414'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
starting to inserting iovs from 100000 to 100000 into pll pl_type_0_71
sdcc.json
resp = ['']
line = 
Traceback (most recent call last):
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 36, in <module>
    main(args)
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 11, in main
    campaign.prepare()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 186, in prepare
    self.set_db_size_dict()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 177, in set_db_size_dict
    x_dict = json.loads(line)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
create_global_tag_statuses()
get_existing_global_tag_statuses()
res.json() = [{'id': 17, 'name': 'unlocked', 'created': '2023-02-03T15:52:41.743025'}]
create_global_tags()
get_existing_global_tags()
res.json() = [{'id': 17, 'name': 'global_tag_0', 'author': 'linogerlach', 'status': 'unlocked', 'payload_lists_count': 1, 'payload_iov_count': 100000, 'created': '2023-02-03T15:52:41.774769', 'updated': '2023-02-03T15:52:41.847378'}]
get_exisitng_payload_types()
res.json() = [{'id': 71, 'name': 'pl_type_0', 'created': '2023-02-03T15:52:41.800361'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
gt global_tag_0 already has a pl for type pl_type_0
get_last_plt_iov_dict()
url = http://test111.apps.usatlas.bnl.gov/api/cdb_rest/payloadiovsfast/?gtName=global_tag_0&majorIOV=2147483647&minorIOV=0
resp.json() = [{'id': 71, 'name': 'pl_type_0_71', 'global_tag': 'global_tag_0', 'payload_type': 'pl_type_0', 'payload_iov': [{'id': 6645005, 'payload_url': 'pl_type_0_71_99999_dummy_file.data', 'checksum': '', 'major_iov': 99999, 'minor_iov': 0, 'major_iov_end': 9223372036854775807, 'minor_iov_end': 9223372036854775807, 'payload_list': 'pl_type_0_71', 'inserted': '2023-02-06T08:37:00.635522'}], 'created': '2023-02-03T15:52:41.830414'}]
get_payload_list_name(global_tag=global_tag_0, pl_type=pl_type_0)
res.json() = {'pl_type_0': 'pl_type_0_71'}
starting to inserting iovs from 100000 to 100000 into pll pl_type_0_71
sdcc.json
resp = ['']
line = 
Traceback (most recent call last):
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 36, in <module>
    main(args)
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 11, in main
    campaign.prepare()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 186, in prepare
    self.set_db_size_dict()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 177, in set_db_size_dict
    x_dict = json.loads(line)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
run.sh: line 11: 32124 Terminated              python scripts/bulk_insert.py --hostname $HOSTNAME --n_gt $n_gt --n_iov $iov_per_pt --n_pt $n_pt
sdcc.json
resp = ['']
line = 
Traceback (most recent call last):
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 36, in <module>
    main(args)
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/run_campaign.py", line 11, in main
    campaign.prepare()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 186, in prepare
    self.set_db_size_dict()
  File "/gpfs/mnt/gpfs02/sphenix/user/lgerlach1/nopayloadtesting/nopayloadtesting/campaign.py", line 177, in set_db_size_dict
    x_dict = json.loads(line)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/stow/Python-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/lib/python3.10/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
